### ISSUE TITLE
Add NpgsqlCidr type to v8 Release Notes

### ISSUE THREAD

**Issue by MaceWindu** [npgsql/doc#309] opened 2023-10-15 16:56 UTC
I see that NpgsqlInet type doesn't support `cidr` anymore and new NpgsqlCidr type was introduced. This change looks like something that should be mentioned in release notes to me.

**Comment by roji** [comment] 2023-10-16 09:20
Duplicate of #307

**Comment by roji** [comment] 2023-10-16 09:21
@MaceWindu thanks. I did this in #307, but for some reason it isn't visible on the site (most probably because a parallel CI build raced with that PR). I'll trigger a new push to live.

**Closed by roji** 2023-10-16 09:21 UTC
